version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    target-branch: "develop"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
