name: Run release-please to prepare release PR

on:
  push:
    branches:
      - main

# Only allow one instance of this workflow to run at a time, per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
